github:
  description: "Apache CouchDB Helm Chart"
  labels:
    - couchdb
    - helm
    - kubernetes
  protected_branches:
    main:
      required_status_checks:
        strict: true
      required_linear_history: true
    gh-pages: {}
  ghp_branch: gh-pages
