{{- if and .Values.persistentVolume.enabled .Values.persistentVolume.existing -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- include "persistentVolume.metadata" . | nindent 2 }}
spec:
  {{- include "persistentVolume.spec" . | nindent 2 }}
{{- end }}
