{{- if and .Values.persistentVolume.enabled .Values.persistentVolume.existing -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.persistentVolume.volumeName }}
spec:
{{- if .Values.persistentVolume.storageClass }}
{{- if (eq "-" .Values.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
  accessModes:
  {{- range .Values.persistentVolume.accessModes }}
    - {{ . | quote }}
  {{- end }}
  capacity:
    storage: {{ .Values.persistentVolume.size }}
{{ toYaml .Values.persistentVolume.volumeSource | indent 2 }}
{{- end }}
